class TransferError(Exception):
    pass


class CloseError(Exception):
    pass
